### ISSUE TITLE
Move from hostname check to ip ranges

### ISSUE THREAD

**Issue by jfoclpf** [roccomuso/is-google#1]
Hi, I realized you use hostname to check if it is google, that's unreliable and prone to spoofing, you should use IP ranges instead

1) You download into memory the google bots ip ranges at the startup of the script from official website
https://developers.google.com/search/docs/crawling-indexing/verifying-googlebot

2) then for every request you check if the ip (`req.ip`) falls within the ranges
https://www.npmjs.com/package/ip-range-check

Just a tip, because this package has potential, but as it is is not reliable

have a great day

**Comment by jfoclpf** [comment]
wait, I see that you use dns reverse function which should be reliable, but it's not efficient, you make a new DNS request for every request, my approach is more efficient for a server

**Comment by roccomuso** [comment]
PRs are welcome

**Comment by jfoclpf** [comment]
Hi there, I eventually made a new package ;)
https://www.npmjs.com/package/express-is-googlecrawler

I'd say yours is more reliable on the long run, since the urls with IP ranges may change; but mine is faster, it doesn't make a DNS request for every inbound request
